### ISSUE TITLE
Changing UI language in document editing view redirects you to start page

### ISSUE THREAD

**Issue by bertab** [tilde-nlp/MateCat#101]
Page should be reloaded with the same project open

**Comment by YourLittleHelper** [comment]
@valterss Language change is not in the scope of hugo cat app, it's handled by hugo itself. It looks like return path on language links doesn't change between Translate/Cat#/ and Translate/Cat#/translate/3/b35ab023fe9f
It might be due to the fact hugo cat app is single page application and can change without reloading. We need to figure out a way to update language change links with current cat app path.

**Comment by valterss** [comment]
@YourLittleHelper, I think the option to fix this is the hugo itself has to handle return url better.

**Comment by YourLittleHelper** [comment]
@valterss Hugo can watch hash changes and update language links or language links can redirect with function calls which checks location hash
https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onhashchange

**Comment by YourLittleHelper** [comment]
Moved to tfs.
